# Site wide configuration

title: "Supeeeer ☀️"
description: "my blog lalala "
logo: profile.jpg # 120x120 px default image used for Twitter summary card
teaser: default.jpg # 400x250 px default teaser image used in image archive grid
locale: en
url: https://supeeeer.github.io
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
paginate: 10
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: supeeeer
  email: supeeeer@icloud.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: profile.jpg # 160x160 px image for author byline
  disqus-shortname:
  github_username: supeeeer

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto
  


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
